name: helloworld
on:
  push: 
    branches: [main]

jobs :
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "This is build"

      - name: test
        run: echo "This is test"

      - name : deploy
        run: echo 'This is deploy'
